model: mowgli
dins: 72,23
douts: 72
input_modalities: "expmap_scaled_20,mel_ddcpca_scaled_20"
output_modalities: expmap_scaled_20
input_lengths: 120,140
output_lengths: 10
output_time_offsets: 120
nlayers: 12
nhead: 10
use_pos_emb_output: True
dhid: 800
dropout: 0
lr_policy: multistep
lr_decay_milestones: [500,750]
learning_rate: 5e-5
gradient_clip_val: 0.5
batch_size: 64
find_unused_parameters: True



