model: transglower
lr_policy: "multistep"
lr_decay_milestones: "[5000,10000]"
learning_rate: 1e-4
dins: "72,23"
douts: "72"
input_modalities: "expmap_scaled_20,mel_ddcpca_scaled_20"
output_modalities: "expmap_scaled_20"
input_lengths: "59,60"
input_seq_lens: "40,41"
output_lengths: "20"
output_time_offset: "40"
nlayers: 4
nhead: 10
use_pos_emb_output: True
dhid: 400
glow_K: 16
dropout: 0
gradient_clip_val: 0.5
batch_size: 8
