model: moglow
lr_policy: "multistep"
network_model: "LSTM"
lr_decay_milestones: "[1000,1500]"
learning_rate: 2e-4
dins: "63,3"
douts: "63"
input_modalities: "position_scaled,moglow_control_scaled"
output_modalities: "position_scaled"
input_lengths: "79,80"
output_lengths: "70"
input_seq_lens: "10,11"
output_time_offset: "10"
dropout: 0
