model: residualflower2
mean_model: transformer
residual_model: transflower
lr_policy: "multistep"
lr_decay_milestones: "[25,50]"
learning_rate: 5e-5
dins: "63,3"
douts: "63"
input_modalities: "position_scaled,moglow_control_scaled"
output_modalities: "position_scaled"
input_lengths: "59,60"
output_lengths: "20"
output_time_offset: "40"
mean_nlayers: 6
mean_nhead: 10
mean_use_pos_emb_output: True
mean_dhid: 800
dropout: 0
gradient_clip_val: 0.5
batch_size: 8
residual_dhid: 800
residual_cond_concat_dims: True
residual_glow_norm_layer: "batchnorm"
residual_glow_bn_momentum: 0.1
residual_scales: "[[4,0], [4,0]]"
residual_num_glow_coupling_blocks: 2
residual_glow_use_attn: True
residual_use_transformer_nn: True
residual_use_pos_emb_coupling: True
residual_use_pos_emb_output: True
