model: transflower
residual: True
dins: "63,3"
douts: "63"
input_modalities: "position_scaled,moglow_control_scaled"
output_modalities: "position_scaled"
input_lengths: "20,21"
output_lengths: "10"
output_time_offset: "20"
n_layer: 4
nhead: 10
scales: "[[16,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_pos_emb_coupling: True
#use_pos_emb_output: True
dhid: 800
cond_concat_dims: True
glow_norm_layer: batchnorm
glow_bn_momentum: 0.1
dropout: 0
lr_policy: multistep
lr_decay_milestones: [25,50]
learning_rate: 5e-5
gradient_clip_vale: 0.5
batch_size: 64



