model: transflower
lr_policy: "multistep"
lr_decay_milestones: "[1000,1500]"
learning_rate: 5e-5
dins: "63,3"
douts: "63"
input_modalities: "position_scaled,moglow_control_scaled"
output_modalities: "position_scaled"
input_lengths: "79,80"
output_lengths: "10"
output_time_offsets: "79"
scales: "[[8,0],[8,0]]"
nlayers: 6
nhead: 10
num_glow_coupling_blocks: 2
cond_concat_dims: True
glow_use_attn: True
use_transformer_nn: True
use_pos_emb_coupling: True
#use_pos_emb_output: True
dhid: 800
glow_norm_layer: "batchnorm"
glow_bn_momentum: 0.1
dropout: 0
conditioning_seq_lens: "10"
gradient_clip_val: 0.5
batch_size: 16
