model: transglower
residual: True
lr_policy: "multistep"
lr_decay_milestones: "[1000,1500]"
learning_rate: 1e-4
dins: "63,3"
douts: "63"
input_modalities: "position_scaled,moglow_control_scaled"
output_modalities: "position_scaled"
input_lengths: "79,80"
output_lengths: "70"
input_seq_lens: "10,11"
output_time_offset: "10"
nlayers: 4
nhead: 10
use_pos_emb_output: True
dhid: 400
glow_K: 16
dropout: 0
gradient_clip_val: 0.5
batch_size: 8
