model: transfusion
dins: 63,85
douts: 63
input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_scaled_20
#input_lengths: 60,80
#output_time_offsets: 60
input_lengths: 120,140
output_time_offsets: 120
output_lengths: 1
num_diff_steps: 50
num_sampling_steps: 50
nhead: 8
nlayers: 12
diffu_depth: 8
diffu_model_mean_type: START_X
#diffu_model_var_type: FIXED_SMALL
#diffu_model_var_type: FIXED_LARGE
#diffu_model_var_type: LEARNED_RANGE
dhid: 800
dhid_diffu: 800 #need to allow for this to be diff from dhid
diffu_patch_size: (1,3)
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#cond_concat_dims: True
#conditioning_seq_lens: 100
dropout: 0
#lr_policy: cosine
#lr_policy: plateau
#lr_policy: multistep
#lr_decay_milestones: "[200]"
lr_policy: LinearWarmupCosineAnnealing
optimizer: adamw
#learning_rate: 1e-4
learning_rate: 1e-5
gradient_clip_val: 0.0
batch_size: 64
