model: transfusion
dins: 63,85
douts: 63
input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_scaled_20
input_lengths: 150,120
output_lengths: 1
output_time_offsets: 120
input_dropouts: 0,0
cond_dropout_probs: "0.0"
num_diff_steps: 50
num_sampling_steps: 50
nhead: 8
nlayers: 8
diffu_depth: 4
diffu_model_mean_type: START_X
diffu_model_var_type: FIXED_SMALL
#diffu_model_var_type: FIXED_LARGE
#diffu_model_var_type: LEARNED_RANGE
dhid: 800
dhid_diffu: 600 #need to allow for this to be diff from dhid
diffu_patch_size: (1,3)
#diffu_patch_size: (1,21)
#diffu_patch_size: (1,1)
diffu_scale_betas: 20
#diffu_patch_size: (1,1)
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#cond_concat_dims: True
conditioning_seq_lens: 15
diffu_concat_conds: True
dropout: 0
#lr_policy: cosine
#lr_policy: plateau
#lr_policy: multistep
#lr_decay_milestones: "[200]"
lr_policy: plateau
#lr_policy: step
#lr_decay_milestones: [100,200,400,800,1600,3200,6400]
#lr_decay_iters: 1
lr_decay_factor: 0.5
scheduler_interval: step
lr_scheduler_frequency: 3000
lr_plateau_patience: 2
lr_plateau_threshold: 0.001
plateau_min_lr: 1e-7
#lr_policy: LinearWarmupCosineAnnealing
optimizer: adamw
#optimizer: adam
learning_rate: 1e-4
#learning_rate: 1e-2
gradient_clip_val: 10
batch_size: 84
#batch_size: 128
#batch_size: 28

