model: transfusion
dins: 63,85
douts: 63
input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_scaled_20
input_lengths: 60,80
output_time_offsets: 60
output_lengths: 1
num_diff_steps: 50
num_sampling_steps: 50
nhead: 10
diffu_depth: 6
dhid: 800
dhid_diffu: 800 #need to allow for this to be diff from dhid
diffu_patch_size: (1,3)
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#cond_concat_dims: True
#conditioning_seq_lens: 100
dropout: 0
lr_policy: cosine
#lr_policy: multistep
#lr_decay_milestones: "[200]"
learning_rate: 1e-3
gradient_clip_val: 0.5
batch_size: 64



