model: transflower
dins: 72,103
douts: 72
input_modalities: expmap_scaled,mel_ddcpca_scaled
output_modalities: expmap_scaled
input_lengths: 60,120
output_lengths: 10
output_time_offsets: 60
n_layer: 4
nhead: 10
scales: "[[4,0], [4,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_pos_emb_coupling: True
use_pos_emb_output: True
dhid: 800
cond_concat_dims: True
glow_norm_layer: batchnorm
glow_bn_momentum: 0.1
dropout: 0
lr_policy: multistep
lr_decay_milestones: [25,50]
learning_rate: 5e-5
gradient_clip_vale: 0.5
batch_size: 64



