model: transglower
lr_policy: "multistep"
lr_decay_milestones: "[5000,10000]"
learning_rate: 1e-4
dins: "72,103"
douts: "72"
input_modalities: "expmap_scaled,mel_ddcpca_scaled"
output_modalities: "expmap_scaled"
input_lengths: "29,30"
input_seq_lens: "10,11"
output_lengths: "20"
output_time_offset: "10"
nlayers: 4
nhead: 10
use_pos_emb_output: True
dhid: 800
glow_K: 16
dropout: 0
gradient_clip_val: 0.5
batch_size: 8
