model: transflowpp
lr_policy: "multistep"
lr_decay_milestones: "[5000,10000]"
learning_rate: 1e-4
dins: "219,103"
douts: "219"
input_modalities: "joint_angles_scaled,mel_ddcpca_scaled"
output_modalities: "joint_angles_scaled"
input_lengths: "60,120"
output_lengths: "10"
output_time_offset: "60"
nlayers: 4
nhead: 10
scales: "[[4,0],[4,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
dhid: 200
dropout: 0
gradient_clip_val: 0.5
batch_size: 32
