model: transflower
zero_padding: true
dins: 1,256,18,8
douts: 8,1
input_modalities: "npz.times_to_go,annotation_simp_wnoun,obs_cont_single_nocol_noarm_scaled,npz.acts_scaled"
output_modalities: npz.acts_scaled,npz.times_to_go
input_mod_masks: "1 1 1 1,0 1 1 1"
use_shared_crossmodal_encoder: True
input_lengths: 1,10,1,1
output_lengths: 1,1
output_time_offsets: 1,1
input_dropouts: 0,0,0,0.1
input_proc_types: none,single,none,none
input_types: c,d,c,c
output_proc_types: none,none
#output_types: c
input_num_tokens: 0,73,0,0
nlayers: 12
nhead: 10
scales: "[[24,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#flow_dist: studentT
dhid: 800
dhid_flow: 800
num_heads_flow: 10
cond_concat_dims: True
#conditioning_seq_lens: 100
#glow_norm_layer: batchnorm
glow_norm_layer: actnorm
glow_bn_momentum: 0.1
dropout: 0
#lr_policy: cosine
#lr_policy: multistep
lr_policy: plateau
#lr_decay_milestones: [1,2,4,8,16,32,64]
lr_decay_factor: 0.5
learning_rate: 1e-4
gradient_clip_val: 100
#batch_size: 128
batch_size: 64



