model: moglow
zero_padding: true
use_one_hot: true
dins: 67,125,8
douts: 8
input_modalities: "annotation,npz.obs_scaled,npz.acts_scaled"
output_modalities: npz.acts_scaled
input_lengths: 11,119,119
input_seq_lens: 11,60,60
output_lengths: 60
output_time_offsets: 60
input_proc_types: single,none,none
input_types: d,c,c
output_proc_types: none
#output_types: c
input_num_tokens: 67,0,0
lr_policy: "plateau"
learning_rate: 1e-3
flow_dist: studentT
glow_K: 24
dhid: 128
dropout: 0.1
gradient_clip_val: 10
batch_size: 100
#batch_size: 8
