model: transflower
zero_padding: true
dins: 10,2
douts: 2
input_modalities: "obs,acts"
output_modalities: acts
input_lengths: 1,1
output_lengths: 1
output_time_offsets: 1
input_dropouts: 0,0
input_proc_types: none,none
input_types: c,c
output_proc_types: none
#output_types: c
input_num_tokens: 0,0
nlayers: 12
nhead: 10
scales: "[[16,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#flow_dist: studentT
dhid: 800
dhid_flow: 800
num_heads_flow: 10
cond_concat_dims: True
#conditioning_seq_lens: 100
#glow_norm_layer: batchnorm
glow_norm_layer: actnorm
glow_bn_momentum: 0.1
dropout: 0
#lr_policy: cosine
#lr_policy: multistep
lr_policy: plateau
#lr_decay_milestones: [1,2,4,8,16,32,64]
lr_decay_factor: 0.5
learning_rate: 1e-4
gradient_clip_val: 100
#batch_size: 128
batch_size: 64



