model: discrete
dins: 3,29
douts: 29
input_modalities: "root_pos_scaled,rel_feats_scaled"
output_modalities: rel_feats_scaled
input_lengths: 120,120
#output_lengths: 10
output_lengths: 1
num_tokens: 256
output_time_offsets: 120
nlayers: 12
nhead: 10
#vae_dhid: 256
#vae_codebook_dim: 512
#vae_num_layers: 4
use_pos_emb_output: True
dhid: 800
#prior_nlayers: 24
out_dropout: 0
#lr_policy: multistep
#lr_decay_milestones: [100,500]
#learning_rate: 7e-5
learning_rate: 1e-5
#lr_policy: LinearWarmupCosineAnnealing
lr_policy: exponential
lr_decay_factor: 0.98
gradient_clip_val: 0.5
batch_size: 94
#find_unused_parameters: True
#precision: 16
#plugins: deepspeed
#optimizer: adamw
optimizer: adam
#amp_backend: apex
#amp_level: O1
