model: transflower
dins: 1,21
douts: 21
input_modalities: "speech.wav_envelope_scaled,motion_features_scaled1"
output_modalities: motion_features_scaled1
#input_lengths: 61,60
input_lengths: 60,60
output_lengths: 1
output_time_offsets: 60
input_dropouts: 0,0
nlayers: 12
nhead: 10
scales: "[[24,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#flow_dist: studentT
dhid: 800
dhid_flow: 800
num_heads_flow: 10
cond_concat_dims: True
#conditioning_seq_lens: 100
glow_norm_layer: batchnorm
#glow_norm_layer: actnorm
glow_bn_momentum: 0.1
dropout: 0
#lr_policy: cosine
lr_policy: multistep
#lr_policy: plateau
#lr_policy: step
lr_decay_milestones: "[1000,2000,4000,8000,16000,32000,64000]"
#lr_decay_iters: 1
lr_decay_factor: 0.5
scheduler_interval: step
#lr_scheduler_frequency: 1000
#lr_plateau_patience: 1
#lr_plateau_threshold: 0.001
#lr_policy: LinearWarmupCosineAnnealing
#optimizer: adamw
optimizer: adam
learning_rate: 1e-5
#learning_rate: 1e-2
gradient_clip_val: 1
batch_size: 48
#batch_size: 128
#batch_size: 28



