model: transfusion
dins: 1,19
douts: 19
input_modalities: "speech.wav_envelope_scaled,motion_features_scaled2"
output_modalities: motion_features_scaled2
input_lengths: 31,30
output_lengths: 1
output_time_offsets: 30
num_diff_steps: 50
num_sampling_steps: 50
nhead: 8
nlayers: 12
diffu_depth: 8
diffu_model_mean_type: START_X
diffu_model_var_type: FIXED_SMALL
#diffu_model_var_type: FIXED_LARGE
#diffu_model_var_type: LEARNED_RANGE
dhid: 960
dhid_diffu: 512 #need to allow for this to be diff from dhid
diffu_patch_size: (1,19)
#diffu_patch_size: (1,1)
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_output: True
#cond_concat_dims: True
#conditioning_seq_lens: 100
dropout: 0
#lr_policy: cosine
#lr_policy: plateau
#lr_policy: multistep
#lr_decay_milestones: "[200]"
lr_policy: LinearWarmupCosineAnnealing
optimizer: adamw
learning_rate: 1e-4
#learning_rate: 1e-5
gradient_clip_val: 0.0
#batch_size: 64
batch_size: 84
scheduler_interval: step

