model: moglow
lr_policy: "multistep"
lr_decay_milestones: "[500,1000]"
learning_rate: 1e-4
dins: "69,85"
douts: "69"
input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
output_modalities: "expmap_scaled_20"
input_lengths: "119,129"
input_seq_lens: "40,50"
output_lengths: "80"
output_time_offsets: "40"
glow_K: 16
dropout: 0
gradient_clip_val: 0.5
batch_size: 64
