model: moglow
#lr_policy: "multistep"
#lr_decay_milestones: "[100,200]"
lr_policy: cosine
learning_rate: 1e-3
#dins: "69,85"
dins: 16,67,85
use_one_hot: true
#douts: "69"
douts: "67"
input_modalities: "dance_style,expmap_cr_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_cr_scaled_20
input_proc_types: tile,none,none
input_types: d,c,c
input_num_tokens: 16,0,0
input_lengths: "60,119,139"
input_seq_lens: "1,60,80"
output_lengths: "60"
output_time_offsets: "60"
flow_dist: studentT
network_model: transformer
#network_model: LSTM
use_projection: true
glow_K: 24
dhid: 512
flow_coupling_dmodel: 400
flow_coupling_nheads: 10
dropout: 0.1
gradient_clip_val: 0.5
batch_size: 100
#batch_size: 8
