model: moglow
lr_policy: "multistep"
lr_decay_milestones: "[100,200]"
learning_rate: 1e-3
#dins: "69,85"
dins: "67,85"
#douts: "69"
douts: "67"
#input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
input_modalities: "expmap_cr_scaled_20,audio_feats_scaled_20"
output_modalities: "expmap_cr_scaled_20"
input_lengths: "119,139"
input_seq_lens: "60,80"
output_lengths: "60"
output_time_offsets: "60"
flow_dist: studentT
glow_K: 24
dhid: 128
dropout: 0.1
gradient_clip_val: 0.5
batch_size: 100
network_model: transformer
#batch_size: 8
