model: moglow
lr_policy: "multistep"
lr_decay_milestones: "[1000,1500]"
learning_rate: 6e-5
dins: "72,23"
douts: "72"
input_modalities: "expmap_scaled_20,mel_ddcpca_scaled_20"
output_modalities: "expmap_scaled_20"
input_lengths: "119,129"
input_seq_lens: "40,50"
output_lengths: "80"
output_time_offsets: "40"
glow_K: 16
dropout: 0
gradient_clip_val: 0.5
batch_size: 64
