model: mowgli
dins: 69,85
douts: 69
input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_scaled_20
input_lengths: 120,140
#output_lengths: 10
output_lengths: 3
output_time_offsets: 120
nlayers: 12
nhead: 10
vae_dhid: 128
vae_num_layers: 3
#use_pos_emb_output: True
dhid: 800
#prior_nlayers: 24
prior_dropout: 0
#dropout: 0.1
#max_prior_loss_weight: 1
max_prior_loss_weight: 0
#lr_policy: multistep
#lr_decay_milestones: [100,500]
#learning_rate: 7e-5
learning_rate: 1e-4
#lr_policy: LinearWarmupCosineAnnealing
lr_policy: cosine
gradient_clip_val: 0.5
batch_size: 256
find_unused_parameters: True
#precision: 16
#plugins: deepspeed
optimizer: adamw
cond_vae: false
#amp_backend: apex
#amp_level: O1
