model: transflower
dins: 69,85
douts: 69
input_modalities: "expmap_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_scaled_20
input_lengths: 120,140
output_lengths: 3
output_time_offsets: 120
input_proc_types: end,end
input_types: c,c
input_num_tokens: 0,0
nlayers: 12
nhead: 10
scales: "[[16,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
#use_rel_pos_emb_coupling: True
#use_rel_pos_emb_output: True
use_pos_emb_output: True
use_rel_pos_emb_inputs: True
dhid: 800
dhid_flow: 800
num_heads_flow: 10
cond_concat_dims: True
#glow_norm_layer: batchnorm
glow_norm_layer: actnorm
glow_bn_momentum: 0.1
dropout: 0
#lr_policy: cosine
lr_policy: multistep
lr_decay_milestones: [200,400]
learning_rate: 2e-5
#learning_rate: 1e-5
gradient_clip_val: 0.5
batch_size: 84
