model: transglower
lr_policy: "multistep"
lr_decay_milestones: "[50,100]"
learning_rate: 7e-5
dins: "67,85"
douts: "67"
input_modalities: "expmap_cr_scaled_20,audio_feats_scaled_20"
output_modalities: "expmap_cr_scaled_20"
input_lengths: "122,142"
input_seq_lens: "120,140"
output_lengths: "3"
output_time_offsets: "120"
nlayers: 12
nhead: 10
use_pos_emb_output: True
dhid: 800
glow_K: 16
dropout: 0
gradient_clip_val: 0.5
batch_size: 32
