model: transflower
dins: 256,67,85
#dins: 128,67,85
douts: 67
input_modalities: "dance_style,expmap_cr_scaled_20,audio_feats_scaled_20"
output_modalities: expmap_cr_scaled_20
input_lengths: 1,120,140
output_lengths: 1
output_time_offsets: 120
input_fix_length_types: single,end,end
input_types: d,c,c
input_num_tokens: 16,0,0
#nlayers: 4
nlayers: 10
nhead: 10
scales: "[[20,0]]"
#num_glow_coupling_blocks: 3
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_rel_pos_emb_inputs: True
use_pos_emb_output: True
#use_pos_emb_coupling: True
#use_pos_emb_coupling: False
#use_pos_emb_output: True
flow_dist: studentT
dhid: 800
#dhid_flow: 800
#num_heads_flow: 10
cond_concat_dims: True
#conditioning_seq_lens: 261
#glow_norm_layer: batchnorm
glow_norm_layer: actnorm
glow_bn_momentum: 0.1
dropout: 0
#lr_policy: cosine
lr_policy: multistep
#lr_decay_milestones: [40,80]
lr_decay_milestones: [4,8]
learning_rate: 1e-4
#optimizer: adamw
optimizer: adam
#optimizer: madgrad
gradient_clip_val: 0.5
#batch_size: 32
batch_size: 64
